### PR TITLE
Upload db-strings.txt to S3.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@jgmize r?

**Comment by glogiotatidis** [comment]
A bit background info: makemessages command failed a couple of times [0] due to a deis cli string parsing error. This was an opportunity to replace `cat` with proper s3 uploading of db-strings.txt as we had discussed ealier.

[0] https://ci.masterfirefoxos.com/job/masterfirefoxos_makemessages/69/console

**Comment by jgmize** [comment]
I think the [eventually consistent](http://www.stackdriver.com/eventual-consistency-really-eventual/) nature of s3 will introduce more problems than this solves. Reusing the same filename will result in stale reads, and using unique urls will result in 404s when the file isn't available yet for the http request.

**Comment by glogiotatidis** [comment]
Hey, you're the one to suggest S3 in the first place! :P 

Kidding aside you have a valid point, I built an improved solution based on what we have. Tell what you think about #92

**Pull request closed without merging**
