### PR TITLE
Import legacy videos to youtube

### PR DESCRIPTION
**Pull request by jgmize**
This builds on #67 and #68 and adds legacy video to youtube import.

### CODE REVIEW

**Comment by jgmize** [comment]
TODO:
- [x] import english videos
- [ ] import non-english videos and map translations in .po files

**Comment by jgmize** [comment]
rebased off latest #68; this *should* be good to review (and possibly merge) after that lands. Removing WIP label: will follow up with translation processing in separate PR.

**Comment by glogiotatidis** [comment]
Tested the import functionality and cross checked the videos imported. Besides the two notes everything looks good. 

Great work as always @jgmize, thanks! r+wc  :sparkles:

**Comment by jgmize** [comment]
@glogiotatidis thanks for your excellent attention to detail on catching the mismatched titles. The issue is caused by duplicate source filenames across versions in the legacy json. Fixing this automatically will require adding version info to data structure stored in video_path_to_youtube_id.json, and the value of fixing it in the script vs manually in the admin for just two video ids is debatable for just the English videos addressed by this PR. It will, however, clearly be necessary to match up the versions for the non-english videos,

**Comment by jgmize** [comment]
@glogiotatidis after discussing things with @bensternthal, we decided attempting to automate matching up the various version and languages in processing the legacy json would require more effort than doing it manually on top of the work that's already been done here. I'm going to go ahead and merge this as-is with its known limitations, and then we'll fill the rest in manually. I'll do the first example translation of the youtube ids and document the process, and @bensternthal has generously volunteered to do the rest of the legacy data, and since this is the process we'll be using for all the new stuff anyway, we'll be very familiar with it and ready for user training for the new 2.0 videos.

**Pull request merged**
