### PR TITLE
Remove alignment and indent buttons from TinyMCE.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by jgmize** [comment]
@glogiotatidis would you mind rebasing?
@craigcook once the rebase is done, would you mind testing this locally?

**Comment by glogiotatidis** [comment]
Rebased!

**Comment by craigcook** [comment]
Looks good to me! The alignment options are still in the format dropdown in case people *really* need them, though I'd strongly discourage authors from using them at all. I forget if we talked about that before... I'm trying to think of a realistic use-case for when an author might need to change text alignment and not coming up with one, so maybe better to remove them from the menu as well?

**Comment by glogiotatidis** [comment]
Removed the alignment options from the format dropdown as well. We can customize the dropdown even more if we want in the future, to add to remove options.

**Comment by jgmize** [comment]
@glogiotatidis would you mind rebasing again? I think we're good to merge after that.

**Comment by glogiotatidis** [comment]
Aaand rebased!

**Comment by glogiotatidis** [comment]
test this please

**Pull request merged**
