### PR TITLE
Fix bug 1133880 - Layout for RTL

### PR DESCRIPTION
**Pull request by craigcook**
Also some special font rules for some locales.

Testing locally is a little clunky without a legit RTL language but you can fake it by hardcoding <code>dir="rtl"</code> in base.html (just don't commit it!).

### CODE REVIEW

**Comment by jgmize** [comment]
test this please.

**Comment by bensternthal** [comment]
@craigcook do you want me to pull down locally and test?

**Comment by craigcook** [comment]
> do you want me to pull down locally and test?

Yes please, just to verify I didn't miss anything obvious. I don't suppose we have any Arabic content to test with, or have they not even started because they're waiting for RTL?

**Comment by bensternthal** [comment]
Everything looks good from the front end when testing locally. I tried all the various content types including the quiz.

**Comment by bensternthal** [comment]
@craigcook anything else needed here or can we merge this one?

**Comment by craigcook** [comment]
> anything else needed here or can we merge this one?

No, this should be good to merge (in fact I thought it had already). If Arabic localizers find any issues as they're working they should file bugs and we can fix them as they come up.

**Pull request merged**
