### PR TITLE
Split h2 and h3 tags from text in db and .po files

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
This builds on and potentially supersedes #119. The .po modifications are integrated into the `fix_all_locales()` function, and there are two new functions: `split_db_h2s()` and `split_db_h3s()` also in the `legacy` module.

**Comment by jgmize** [comment]
I've committed and pushed the results of this to https://github.com/jgmize/masterfirefoxos-l10n/tree/pr-120 and if you look just at the diff between the previous commit that stripped the p tags, you can see just the h2 and h3 splits: https://github.com/jgmize/masterfirefoxos-l10n/commit/5a93bd0ec9ea395ce7e3a46e6c0d3d78c477c6e1?diff=split

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
test this please.

**Comment by glogiotatidis** [comment]
I tested this using a db with a production copy and run 

```
from masterfirefoxos.base.utils import unmangle_pages
unmangle_pages()
from legacy import fix_all_locales
fix_all_locales()```

and h2, h3 are still there.

**Comment by jgmize** [comment]
The two new functions I mentioned earlier have to be run manually from the python shell, they aren't called by unmangle_pages. In hindsight I probably should have added them to unmangle_pages.

**Comment by jgmize** [comment]
@glogiotatidis I've updated the pr and `fig run web ./manage.py runscript dehtmlify` should strip  br tags from the db and the .po files now in addition to splitting on the h2 and h3 tags.

**Comment by glogiotatidis** [comment]
Much better! We do have a few annoying h3's `<h3><em>"I have never had a smartphone."</em></h3>` which persist.

Also some the resulting strings in the database start with space, so we'll need to trim them. Actually we probably need a post_save signal handler to trim all text. Not doing so can result in unmatched translations. I 'll work on this tomorrow.

**Comment by glogiotatidis** [comment]
looks good r+wc

**Comment by jgmize** [comment]
@glogiotatidis I believe the leftover `<h3>` you found must have been from an older db restore, because I didn't have it on mine which I restored from prod just prior to working on this PR, and I just restored again to double check. All of the `<h3>`s in the later version of the db were at the end of the text, which is why I wrote the function to explicitly only handle that case. Good point on stripping the leading and trailing white space; I've added https://github.com/mozilla/masterfirefoxos/commit/ca347063712a7c30e421bdf4b3c19d4f80ac2934 to address the existing data, and the post_save signal handler sounds like a reasonable approach for new entries.

**Comment by jgmize** [comment]
@glogiotatidis if that last commit looks good to you, I think we're good to merge and run against prod :)

**Comment by glogiotatidis** [comment]
Yes! thanks @jgmize :)

**Pull request merged**
