### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by cargoworker** [comment]
Can one of the admins verify this patch?

**Comment by glogiotatidis** [comment]
replaced by https://github.com/mozilla/masterfirefoxos/pull/141

**Comment by glogiotatidis** [comment]
@groovecoder because we use peep, requires.io automatic pull requests are no use to us and we rely on emails. Can you please turn auto-prs on masterfirefoxos?

Thanks!

**Comment by groovecoder** [comment]
I assume you meant please turn **off** auto-prs? Yes, I disabled them. I'm not sure why they suddenly became re-enabled. :(

**Comment by glogiotatidis** [comment]
yes, that's what I meant. thnx!

**Pull request closed without merging**
