### PR TITLE
Split image paragraph h3s

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
I run this against a prod db copy (from 2015-02-20):
 * I verify that h3s are removed
 * Text previously wrapped in h3s is now in subheader_3

I found the following issue: Text in subheader_3 has html tags  `<em>"I have never had a smartphone."</em>` and we don't allow html tags in subheaders and in title.

**Comment by jgmize** [comment]
Good point on the remaining `<em>` tags-- I was thinking they were ok after a discussion with @bensternthal about whether to strip them or not, but I forgot that we don't allow them within headers. I'll update this to strip them.

**Comment by glogiotatidis** [comment]
works! r+

**Pull request merged**
