### PR TITLE
Add /static/revision.txt

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
test this please

**Comment by glogiotatidis** [comment]
@jgmize r?

**Comment by jgmize** [comment]
@glogiotatidis this is missing the script that actually generates /static/revision.txt.

**Comment by glogiotatidis** [comment]
it's in the dockerfile https://github.com/mozilla/masterfirefoxos/pull/28/files#diff-3254677a7917c6c01f55212f86c57fbfR9

do you need something more @jgmize ?

**Comment by glogiotatidis** [comment]
test this please

**Comment by jgmize** [comment]
Oh, my mistake. Thanks @glogiotatidis!

**Pull request merged**
