### PR TITLE
Add makemessages_all_locales script

### PR DESCRIPTION
**Pull request by jgmize**
Call makemessages for all locales added to settings.LANGUAGES
Call new script from bin/jenkins/mamekessages.sh

### CODE REVIEW

**Comment by jgmize** [comment]
`./manage.py makemessages -a` only updates existing locales; new locales have to be explicitly included.

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by jgmize** [comment]
I used the script from this PR, together with the settings from #162 and a copy of the prod db-strings.txt and the cleanup_po script for https://github.com/mozilla/masterfirefoxos-l10n/commit/91ec996a3b2afb4b69e6e3e2e6ac79dd77a3d727

**Comment by glogiotatidis** [comment]
lgtm r+

**Pull request merged**
