### PR TITLE
Implement alternative youtube l10n

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@bensternthal r?

**Comment by bensternthal** [comment]
I spot checked a few and it looks good. I noticed 2.0 is not in here... if that is just because we dont have the translations yet than this is R+

**Comment by jgmize** [comment]
Right, there's nothing version specific in the mapping, I just added comments to make it easier. We'll just add the 2.0 YouTube ids when we have them.

**Comment by glogiotatidis** [comment]
I'm sure that there is a good reason for this but on first sight it goes towards the wrong direction, i.e. adding fxos documentation related info on the settings file instead of the database. Do we have a bug, email or something explaining this?

**Comment by jgmize** [comment]
@glogiotatidis we discovered some issues where the localizers had "fixed" the youtube ids to match the English youtube ids. Given the timing of the launch, I decided to prioritize speed of implementation over "user friendliness" for now. We can certainly add a db implementation later with a nice friendly admin.

**Pull request merged**
