### PR TITLE
Fix Bug 1158961: Enable French 2.0

### PR DESCRIPTION
**Pull request by bensternthal**

### CODE REVIEW

**Comment by bensternthal** [comment]
@glogiotatidis @jgmize so this minor change caused a build failure. However looking at the output in jenkins I see some errors related to peep.

**Comment by bensternthal** [comment]
test this please

**Comment by bensternthal** [comment]
Build passing now...perhaps DNS funkyness... regardless I will wait for one of you to be around before merging.

**Comment by glogiotatidis** [comment]
Thanks Ben!

**Pull request merged**
