### PR TITLE
Initial Gulp File Including Compilation For Stylus

### PR DESCRIPTION
**Pull request by bensternthal**
Removed un-needed stylus entry.

@craigcook very basic, I figure we can flush out the tasks & docs once there are more files.

### CODE REVIEW

**Comment by jgmize** [comment]
This isn't a blocker at all for this PR, but it would be nice to have source maps. What do you think about adding something like https://github.com/stevelacy/gulp-stylus/blob/master/examples/gulpfile.js#L58-L76 to this?

**Comment by bensternthal** [comment]
@jgmize yep id like to add that and the browser refresh in a future PR, this is the initial version to get craig up and running

**Comment by craigcook** [comment]
Agreed that we should use source maps (I'd already added them in my working branch for the home page but that hasn't landed yet). Ben update the gulp script in another PR.

**Comment by bensternthal** [comment]
Yep the latter.

**Comment by craigcook** [comment]
We're committing both and I'll eventually document it (I added a readme in /css but need to cover it in the regular dev docs as well).

**Pull request merged**
