### PR TITLE
Skinning quiz pages

### PR DESCRIPTION
**Pull request by craigcook**

### CODE REVIEW

**Comment by bensternthal** [comment]
Testing this locally the formatting does not look right. I checked the dev tools and did not see anything obvious missing. Attached be what I see:

screen shot 2015-02-17 at 7 48 24 pm

**Comment by bensternthal** [comment]
Viewing source.. there is some funky paragraph stuff afoot.

screen shot 2015-02-17 at 7 56 38 pm

**Comment by jgmize** [comment]
@bensternthal the style issues you're seeing locally are likely due to the p tags in your local db, because I am not seeing them locally. You should be able to remove them by running `fig run web ./manage.py runscript dehtmlify`.

**Comment by jgmize** [comment]
This lgtm locally with my 'dehtmlified' db. Thanks @craigcook

**Comment by jgmize** [comment]
https://prod.masterfirefoxos.com/en/2-0/take-the-challenge/ lgtm :+1:

**Comment by craigcook** [comment]
Yeah, that's the result of the old auto-generated paragraphs in the update template; you end up with nested paragraphs and everything falls apart. It looks much better with the cleaned up content.

**Pull request merged**
