### PR TITLE
[bug 1135114] Strip all TextFields and CharFields in db.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
To run it: `echo "from legacy import strip_all_fields; strip_all_fields()" | ./manage.py shell`

**Comment by glogiotatidis** [comment]
@jgmize r?

**Comment by glogiotatidis** [comment]
complements #136

**Comment by jgmize** [comment]
Thanks @glogiotatidis

**Pull request merged**
