### PR TITLE
 Enable pt-br version 1.1 and 2.0 on production. 

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@jgmize r?

**Comment by bensternthal** [comment]
Tested PR locally R+ 

However github is saying merge with caution!

**Comment by glogiotatidis** [comment]
test this please

**Comment by glogiotatidis** [comment]
test this please

**Comment by glogiotatidis** [comment]
> However github is saying merge with caution!

This was due to the DDOS against github that caused the tests to fail as incomplete. Since we now got the green light, i'm merging this. Thanks for testing @bensternthal !

**Pull request merged**
