### PR TITLE
Support ENABLE_ALL_LANGUAGES in homepage redirect

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by jgmize** [comment]
test this please

**Comment by jgmize** [comment]
@glogiotatidis the tests are passing, but jenkins appears to be failing to push the image built for this pr to the docker hub. It's the same story with #156.

**Comment by glogiotatidis** [comment]
test this please

**Comment by glogiotatidis** [comment]
> @glogiotatidis the tests are passing, but jenkins appears to be failing to push the image built for this pr to the docker hub. It's the same story with #156.

it seems docker hub api was failing early today. https://status.docker.com/

**Comment by glogiotatidis** [comment]
:rocket: r+

**Pull request merged**
