### PR TITLE
Move all non-en locales to pending_locales

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@bensternthal r?

**Comment by jgmize** [comment]
Note that I intentionally left the locales listed in [bug 1135877](https://bugzilla.mozilla.org/show_bug.cgi?id=1135877) out of this PR and intend to add them separately after this is merged.

**Comment by bensternthal** [comment]
Tested locally R+

**Comment by jgmize** [comment]
I tested this locally to make sure that the pending_locales setting  worked as expected, including a full run through the `./manage.py runscript db_strings`, `./manage.py makemessages -a --keep-pot`, `./manage.py runscript cleanup_po` gamut and compared the resulting po files to the current master, and everything seems in order.

**Pull request merged**
