### PR TITLE
Add page caching

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Simple page caching using memory but still very effictive. Tested on giorgos-dev app with prod's database.

cache

[ApacheBench results](https://gist.github.com/glogiotatidis/d4ef01fbc7aa4ebfef3a)

**Comment by glogiotatidis** [comment]
@jgmize r?

**Comment by jgmize** [comment]
thanks @glogiotatidis!

**Comment by glogiotatidis** [comment]
btw @jgmize the default caching is 300 secs. i believe we can go way over this for this project. Thoughts?

**Comment by jgmize** [comment]
@glogiotatidis as I mentioned in our chat just now, we could cache for several hours if we ensure that page updates would show quickly for CMS users.  I don't think that the django middleware respects the `Cache-control: no-cache` header, but I'll double check and either add support for that if necessary or figure out a way to invalidate the cache automatically for pages that are only viewable by authenticated users.

**Pull request merged**
