### PR TITLE
Strip p tags from DB entries and .po files

### PR DESCRIPTION
**Pull request by jgmize**
Add p tags to utils.unmangle()
Dedupe .po files
Remove extraneous newlines from .po files

### CODE REVIEW

**Comment by jgmize** [comment]
To test locally:
```
fig run web ./manage.py shell_plus
from masterfirefoxos.base.utils import unmangle_pages
unmangle_pages()
from legacy import fix_all_locales
fix_all_locales()
```

The `unmangle_pags()` call will now remove p tags in addition to fixing other "helpful" modifications made previously by TinyMCE before we removed it. The `fix_all_locales()` call will strip p tags (and extraneous newlines, which are currently present in the `it` locale) from all translations and remove the resulting duplicate entries.

**Comment by jgmize** [comment]
I pushed the results of the `fix_all_locales()` function to https://github.com/jgmize/masterfirefoxos-l10n/tree/pr-119 hoping to link to a diff on github, but unfortunately the diffs are too large and I haven't found a way to force github to show them anyway.

**Comment by jgmize** [comment]
@glogiotatidis r?

**Comment by glogiotatidis** [comment]
test this please.

**Comment by glogiotatidis** [comment]
Looks good! A couple of notes:
 - We have lots of `<br><br>` in our db. We want to remove these as well? [Bleach](http://bleach.readthedocs.org/en/latest/) could be useful
 - It would be helpful to create a tiny small `runscript` so we can easily run this on the server using `deis run`

**Comment by glogiotatidis** [comment]
I tested this locally and indeed all `p` tags went away. r+

**Comment by jgmize** [comment]
Thanks @glogiotatidis,  good points on the br tags and the runscript
wrapper.  I'll add that to #120.

**Comment by glogiotatidis** [comment]
Replaced by #120

**Pull request closed without merging**
